### ISSUE TITLE
URLs for featureCatalog.xml could be better

### ISSUE THREAD

**Issue by asonnenschein** [usgin/modelmanager#11]
Each content model version has an associated featureCatalog xml file that is generated through django's templating system.  The url for a featureCatalog xml file looks like:
`http://localhost:8000/featurecatalog/{some-integer}.xml`
Where `{some-integer}` is a number like 1,2,3,4,5.... and content model versions are assigned to integers in alphabetical order by model and then oldest to newest version.

Would it be a better idea to generate these urls so that they reflect their data better?  Something like:
`http://localhost:8000/featurecatalog/activefault/1.9.xml`
Just having integer values is confusing.

Woops, didn't realize this was already an issue #8.

**Comment by smrgeoinfo** [comment]
How much work would that take?
T-Mobile. America's First Nationwide 4G Network

Adrian Sonnenschein notifications@github.com wrote:

Each content model version has an associated featureCatalog xml file that is generated through django's templating system. The url for a featureCatalog xml file looks like:
http://localhost:8000/featurecatalog/{some-integer}.xml
Where {some-integer} is a number like 1,2,3,4,5.... and content model versions are assigned to integers in alphabetical order by model and then oldest to newest version.

Would it be a better idea to generate these urls so that they reflect their data better? Something like:
http://localhost:8000/featurecatalog/activefault/1.9.xml
Just having integer values is confusing.

##

**Comment by asonnenschein** [comment]
Not much, I'm going to go in make some minor changes to the db and then change the query on the backend.  Right now the query is done by django's/pg's default selector, which are db primary keys.  I'm just going to change that to the model label + version number.

**Comment by smrgeoinfo** [comment]
So what do the URL’s to get the featureCatalog.xml look like? We’ll add them to the metadata in the catalog.
steve

Stephen M Richard
Arizona Geological Survey
416 W. Congress  #100
Tucson, AZ
AZGS: 520-770-3500
Office: 520-209-4127
FAX: 520-770-3505

**Comment by asonnenschein** [comment]
To access a featureCatalogue:

`http://localhost:8000/featurecatalog/{content_model}/{model_version}.xml`
`e.g http://localhost:8000/featurecatalog/activefault/1.1.xml`

And a content model:

`http://localhost:8000/contentmodel/{content_model}.json`
`e.g. http://localhost:8000/contentmodel/activefault.json`

None of this stuff is live yet and it can't be until the new data structure is integrated into CKAN, or else validation within CKAN will break.
